language: php

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache/files
    - ${TRAVIS_BUILD_DIR}/travis/module-cache

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

env:
    - ILLUMINATE_VERSION=5.1.*
    - ILLUMINATE_VERSION=5.2.*
    - ILLUMINATE_VERSION=5.3.*
    - ILLUMINATE_VERSION=5.4.*
    - ILLUMINATE_VERSION=5.5.*
    - ILLUMINATE_VERSION=5.5.* COVERAGE=true

matrix:
    # For each PHP version we exclude the coverage env, except for PHP 7.1
    exclude:
        # Test only Laravel 5.1 and 5.2 on PHP 5.5
        - php: 5.5
          env: ILLUMINATE_VERSION=5.3.*
        - php: 5.5
          env: ILLUMINATE_VERSION=5.4.*
        - php: 5.5
          env: ILLUMINATE_VERSION=5.5.*
        - php: 5.5
          env: ILLUMINATE_VERSION=5.5.* COVERAGE=true
        # Don't test Laravel 5.5 on PHP 5.6
        - php: 5.6
          env: ILLUMINATE_VERSION=5.5.*
        - php: 5.6
          env: ILLUMINATE_VERSION=5.5.* COVERAGE=true
        # Test everything on PHP 7.0
        - php: 7.0
          env: ILLUMINATE_VERSION=5.5.* COVERAGE=true
        # Test only Laravel 5.4 and 5.5 on PHP 7.1
        - php: 7.1
          env: ILLUMINATE_VERSION=5.1.*
        - php: 7.1
          env: ILLUMINATE_VERSION=5.2.*
        - php: 7.1
          env: ILLUMINATE_VERSION=5.3.*
        - php: 7.1
          env: ILLUMINATE_VERSION=5.5.*

before_install:
    - phpenv config-rm xdebug.ini
    - sudo apt-get install graphicsmagick
    - sh -c "mkdir -p ${TRAVIS_BUILD_DIR}/travis/module-cache/`php-config --vernum`"
    - pear config-set preferred_state beta
    - pecl channel-update pecl.php.net
    - MODULES="imagick.so:imagick gmagick.so:gmagick" ./scripts/modulecache.sh
    - composer global require hirak/prestissimo --update-no-dev
    - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update --prefer-dist

install: composer update --no-interaction --prefer-dist

script: vendor/bin/phpunit

after_success: if [-n $COVERAGE]; then travis_retry php vendor/bin/coveralls; fi

notifications:
    email: false
    slack:
        secure: ZilkSllOIo1vCtgUJrQ2ZQaCxW4/zpXZSFYL5Scl5o66fkgmymHR+cUqHsz9jHkXEkxOxORG1baRaJDKnyJ2A3XTfscmhOvAOupQ9jzc9M8yzugH7SrxcjDUJ02CX6LcXlOtOvPwPdkHVi9hR/qmx9D4QZEznVmvxZ2HJOVNJ18=
